---
title: "PlotImmuneGDExperiments"
author: "Scott Leighow"
date: '2022-07-30'
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(ggplot2)
library(reshape2)
```


## Import and parse data

```{r}
# Import
counts.df = read.csv("PC9CD19GDCounts_120522.csv",header=T,stringsAsFactors=F)

# Parse
counts.df$Condition = gsub("C","",counts.df$Condition)
counts.df$Replicate = gsub("R","",counts.df$Replicate)
counts.df$Day = as.numeric(gsub("D","",counts.df$Day))

counts.df$Alive = as.numeric(gsub(",","",counts.df$Alive))
counts.df$Resistant = as.numeric(gsub(",","",counts.df$Resistant))
counts.df$Gene.Drive = as.numeric(gsub(",","",counts.df$Gene.Drive))

counts.df$Sensitive = counts.df$Alive-counts.df$Resistant-counts.df$Gene.Drive


# Reshape
counts.rs = melt(counts.df,
                 id.vars=c("Condition","Replicate","Day"),
                 measure.vars=c("Sensitive","Resistant","Gene.Drive"))

# Adjust counts to get counts/well (for different reading protocol)
# All days, counts are in 50 uL
# But for two days (D3 and D6)
#   -we resuspended 50 uL of cell suspension with 200 uL
#   -then transferred 200 uL of cell suspension to 200 uL of media supernatant, which shouldn't have any live cells
D3_6.dil = 250/200*200/400/50*450
# For the other days (D0 and D9+)
#   -we resuspended 50 uL of cell suspension with 200 uL
D0_9.dil = 250/200/50*200

counts.rs$value[counts.rs$Day%in%c(3,6)] = counts.rs$value[counts.rs$Day%in%c(3,6)]*D3_6.dil
counts.rs$value[!counts.rs$Day%in%c(3,6)] = counts.rs$value[!counts.rs$Day%in%c(3,6)]*D0_9.dil


```

## Loop through conditions and plot

```{r}

cndtns = c(1,2)

for (cndtn.i in cndtns) {
  
  sub.counts = counts.rs[counts.rs$Condition==cndtn.i,]
  
  # Aggregate counts
  sub.agg = aggregate(sub.counts$value,
                      by = list(Condition=sub.counts$Condition,
                                Day=sub.counts$Day,
                                Population = sub.counts$variable),
                     FUN = function(x) c(mean=mean(x),sem=sd(x)/sqrt(length(x))))
  sub.agg = do.call(data.frame,sub.agg)
  
  # Remove GFP counts for -GD condition
  if (cndtn.i==1) {
    sub.agg = sub.agg[sub.agg$Population!="Gene.Drive",]
    clrs = c("#2ABAFC","#EE1D23")
  } else {
    clrs = c("#2ABAFC","#EE1D23","#1AD31A")
    }
  
  # Plot
  g = ggplot(sub.agg,aes(x=Day,y=x.mean/1000,color=Population))+theme_bw()+
    geom_point(size=4)+
    geom_line(size=2)+
    geom_errorbar(aes(ymin=(x.mean-x.sem)/1000,ymax=(x.mean+x.sem)/1000),width=0.5,size=1.25)+
    scale_color_manual(values=clrs)+
    ggtitle(paste("Condition",cndtn.i))+
    xlab("Days")+
    ylab("Cell Counts (thousands)")+
    ylim(0,75)+
   theme(
    plot.title = element_text(size=22,face="bold",hjust=0.5),
    axis.title = element_text(size=20,face="bold"),
    axis.text = element_text(size=18,face="bold",color="black"),
    axis.text.x.top = element_blank(),
    legend.title = element_text(size=18,face="bold"),
    legend.text = element_text(size=16,face="bold")
  )+
  guides(color="none")

  print(g)
  ggsave(paste0("PooledCD19GDCondition",cndtn.i,".png"),width=5,height=5)

  
}
```

## Plot inset for condition 2

```{r}

cndtn.i = 2

sub.counts = counts.rs[counts.rs$Condition==cndtn.i,]

# Aggregate counts
sub.agg = aggregate(sub.counts$value,
                    by = list(Condition=sub.counts$Condition,
                              Day=sub.counts$Day,
                              Population = sub.counts$variable),
                   FUN = function(x) c(mean=mean(x),sem=sd(x)/sqrt(length(x))))
sub.agg = do.call(data.frame,sub.agg)

clrs = "#EE1D23"

# Plot
g = ggplot(sub.agg[sub.agg$Population=="Resistant",],aes(x=Day,y=x.mean/1000,color=Population))+theme_bw()+
  geom_point(size=4)+
  geom_line(size=2)+
  geom_errorbar(aes(ymin=(x.mean-x.sem)/1000,ymax=(x.mean+x.sem)/1000),width=0.5,size=1.25)+
  scale_color_manual(values=clrs)+
  ggtitle(paste("Resistant Population"))+
  xlab("Days")+
  ylab("Cell Counts (thousands)")+
  ylim(0,13)+
 theme(
  plot.title = element_text(size=22,face="bold",hjust=0.5),
  axis.title = element_text(size=20,face="bold"),
  axis.text = element_text(size=18,face="bold",color="black"),
  axis.text.x.top = element_blank(),
  legend.title = element_text(size=18,face="bold"),
  legend.text = element_text(size=16,face="bold")
)+
guides(color="none")

print(g)
ggsave("PooledCD19GDCondition2Inset.png",width=5,height=4)


```

