---
title: "PlotTPC1GeneCDriveExperiment"
author: "Scott Leighow"
date: '2022-08-16'
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(ggplot2)
library(reshape2)
```


## Import and parse data

```{r}
counts.df = read.csv("TPC1_GeneDrivePooled.csv",header=T,stringsAsFactors=F)

counts.df$sen = as.numeric(gsub(",","",counts.df$sen))
counts.df$res = as.numeric(gsub(",","",counts.df$res))
counts.df$gd = as.numeric(gsub(",","",counts.df$gd))

# Reshape

counts.rs = melt(counts.df,id.vars=c("condition","replicate","day"))

```

## Loop through conditions and plot

```{r}

cndtns = 1:3

for (i in 1:length(cndtns)) {
  
  cndtn.i = cndtns[i]
  
  sub.counts = counts.rs[counts.rs$condition==cndtn.i,]
  
  # Aggregate counts
  sub.agg = aggregate(sub.counts$value,
                      by = list(condition=sub.counts$condition,
                                day=sub.counts$day,
                                population = sub.counts$variable),
                     FUN = function(x) c(mean=mean(x),sem=sd(x)/sqrt(length(x))))
  sub.agg = do.call(data.frame,sub.agg)
  
  # Remove GFP counts for -GD
  if (cndtn.i==1) {
    sub.agg = sub.agg[sub.agg$population!="gd",]
    sub.agg = sub.agg[sub.agg$day<=16,]
    clrs = c("#2ABAFC","#EE1D23")
  } else if (cndtn.i==2) {
    clrs = c("#2ABAFC","#EE1D23","#1AD31A")
  } else if (cndtn.i==3) {
    sub.agg = sub.agg[sub.agg$day<=20,]
    clrs = c("#2ABAFC","#EE1D23","#1AD31A")
  }
  
  sclng.fctr = 1/15 # counts are in 15 uL, scale for thousand counts in 1 mL
  
  # Plot
  g = ggplot(sub.agg,aes(x=day,y=x.mean*sclng.fctr,color=population))+theme_bw()+
    geom_point(size=4)+
    geom_line(size=2)+
    geom_errorbar(aes(ymin=(x.mean-x.sem)*sclng.fctr,ymax=(x.mean+x.sem)*sclng.fctr),width=0.5,size=1.25)+
    scale_color_manual(values=clrs)+
    ggtitle(paste("Condition",cndtn.i))+
    xlab("Days")+
    ylab("Cell Counts (thousands)")+
    scale_y_continuous(limits=c(0,215),breaks=c(0,100,200))+
    scale_x_continuous(breaks=c(0,10,20,30),labels=c(0,10,20,40))+ # hack to get break in x axis, rather than using ggbreak; will clean up in Illustrator
    # xlim(0,28)+
   theme(
    plot.title = element_text(size=22,face="bold",hjust=0.5),
    axis.title = element_text(size=20,face="bold"),
    axis.text = element_text(size=18,face="bold",color="black"),
    axis.text.x.top = element_blank(),
    legend.title = element_text(size=18,face="bold"),
    legend.text = element_text(size=16,face="bold")
  )+
  guides(color="none")
  
  print(g)
  # ggsave(paste0("TPC1_Condition",cndtn.i,".png"),width=5,height=5)

  
}
```


```{r}
## Plot inset of resistance for condition 2
 cndtn.i = cndtns[2]

sub.counts = counts.rs[counts.rs$condition==cndtn.i,]

# Aggregate counts
sub.agg = aggregate(sub.counts$value,
                    by = list(condition=sub.counts$condition,
                              day=sub.counts$day,
                              population = sub.counts$variable),
                   FUN = function(x) c(mean=mean(x),sem=sd(x)/sqrt(length(x))))
sub.agg = do.call(data.frame,sub.agg)

# Remove GFP counts for -GD
clrs = "#EE1D23"

sclng.fctr = 1/15 # counts are in 15 uL, scale for thousand counts in 1 mL

# Plot
g = ggplot(sub.agg[sub.agg$population=="res",],aes(x=day,y=x.mean*sclng.fctr,color=population))+theme_bw()+
  geom_point(size=4)+
  geom_line(size=2)+
  geom_errorbar(aes(ymin=(x.mean-x.sem)*sclng.fctr,ymax=(x.mean+x.sem)*sclng.fctr),width=0.5,size=1.25)+
  scale_color_manual(values=clrs)+
  ggtitle("Resistant Population")+
  xlab("Time (days)")+
  ylab("Cell Counts (thousands)")+
  scale_y_continuous(breaks=c(0,2,4,6),limits=c(0,6))+
  scale_x_continuous(breaks=c(0,10,20,30),labels=c(0,10,20,40))+ # hack to get break in x axis, rather than using ggbreak; will clean up in Illustrator
  # xlim(0,28)+
 theme(
  plot.title = element_text(size=22,face="bold",hjust=0.5),
  axis.title = element_text(size=20,face="bold"),
  axis.text = element_text(size=18,face="bold",color="black"),
  axis.text.x.top = element_blank(),
  legend.title = element_text(size=18,face="bold"),
  legend.text = element_text(size=16,face="bold")
)+
guides(color="none")

print(g)
# ggsave(paste0("TPC1_Condition2Inset.png"),width=5,height=4)

```